name = "mokumoku-bot"
main = "src/index.ts"
compatibility_date = "2023-12-01"
minify = true

[[d1_databases]]
binding = "DB"
database_name = "prod-mokumoku-bot"
database_id = "{D1_DATABASE_ID}"
migrations_dir = "drizzle"
