name = "mokumoku-bot"
main = "src/index.ts"
compatibility_date = "2023-12-01"
minify = true

[[d1_databases]]
binding = "DB"
database_name = "prod-mokumoku-bot"
database_id = "6220dbaa-af06-4505-953c-5b8af27697b3"
migrations_dir = "drizzle"
